# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelModules = ["v4l2loopback"];
  boot.extraModulePackages = with config.boot.kernelPackages; [v4l2loopback];
  boot.extraModprobeConfig = ''
    options snd_usb_audio vid=0x1235 pid=0x8211 device_setup=1
  '';

  # Usando GRUB xq tiene skins
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    # Detect OS automatically
    useOSProber = true;
    device = "nodev";
    minegrub-theme = {
      enable = true;
      splash = "Say gex!";
      background = "background_options/1.13 - [Aquatic update].png";
      # boot-options-count = 3;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-label/swap";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # hardware.pulseaudio.support32Bit = true;
  ### AMD STUFF
  hardware.graphics = {
    # Mesa
    enable = true;
    extraPackages = with pkgs; [mangohud rocmPackages.clr.icd];
    extraPackages32 = with pkgs; [pkgsi686Linux.mangohud];
    enable32Bit = true;
  };
  hardware.amdgpu.opencl.enable = true;

  i18n.defaultLocale = "es_CL.UTF-8";
  # Set your time zone.
  time.timeZone = "America/Santiago";
  time.hardwareClockInLocalTime = true;

  # Force radv
  networking.hostName = "atrii-trans"; # Define your hostname.
}
