# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.loader.efi.canTouchEfiVariables = lib.mkForce false;

  fileSystems."/" = {
    device = "/dev/mapper/crypted";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-label/nixos";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A82D-0A0E";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  hardware.asahi = {
    enable = true;
    peripheralFirmwareDirectory = ./vendorfw;
  };

  hardware.apple.touchBar = {
    enable = true;
  };
  uri.steam.enable = lib.mkForce false;

  networking.hostName = "manzana";
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
