# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelPackages = pkgs.cachyosKernels.linuxPackages-cachyos-latest-lto-x86_64-v3;
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.kernelModules = [ "v4l2loopback" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
  boot.extraModprobeConfig = ''
    options snd_usb_audio vid=0x1235 pid=0x8211 device_setup=1
  '';

  # Usando limine xq me gusta cachy
  boot.loader.limine = {
    enable = true;
    style.wallpapers = [
      pkgs.nixos-artwork.wallpapers.catppuccin-frappe.gnomeFilePath
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  fileSystems."/home/lal1tx/bocchi" = {
    device = "/dev/disk/by-label/data";
    fsType = "ext4";
  };

  swapDevices = [
    {
      device = "/dev/disk/by-label/swap";
      # randomEncryption.enable = true;
    }
  ];

  services.fprintd = {
    enable = true;
    package = pkgs.fprintd.overrideAttrs (_: {
      buildInputs = with pkgs; [
        glib
        polkit
        nss
        pam
        systemd
        (libfprint.overrideAttrs (_: {
          version = "1.94.0-sketchy";
          src = pkgs.fetchFromGitLab {
            domain = "gitlab.freedesktop.org";
            owner = "depau";
            repo = "libfprint";
            rev = "elanmoc2";
            hash = "sha256-dxMls9Z5J9agesuNC46OoXAiYW/GcqWEEiAF7Y7DfwQ=";
          };
          doInstallCheck = false;
          dontCheck = true;
          patches = [
            ./disable-tests.patch
          ];
        }))
      ];
    });
  };

  systemd.tmpfiles.rules = [
    "Z /sys/class/powercap/intel-rapl:0/energy_uj 0444 root root - -"
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Bluetooth
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };

  # hardware.pulseaudio.support32Bit = true;
  ### Intel Stuff
  hardware.graphics = {
    # Mesa
    enable = true;
    extraPackages = with pkgs; [ mangohud ];
    extraPackages32 = with pkgs; [ pkgsi686Linux.mangohud ];
    enable32Bit = true;
  };
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  i18n.defaultLocale = "es_CL.UTF-8";
  # Set your time zone.
  time.timeZone = "America/Santiago";
  time.hardwareClockInLocalTime = true;

  # Power saving
  services.thermald.enable = true;

  environment.systemPackages = with pkgs; [
    nvtopPackages.intel
    btop
  ];

  # Force radv
  networking.hostName = "teto"; # Define your hostname.
}
